# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Mark Nachazel
tagline:          ''
description:      ''
url:              http://marknach.github.io

author:
  name:           'Mark Nachazel'
  url:            https://twitter.com/marknach

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/marknach
