# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mark Nachazel
tagline:          ''
description:      'Base theme for Jekyll themes by @mdo.'

author:
  name:           'Mark Nachazel'
  url:            https://twitter.com/marknach

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
