# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mark Nachazel
tagline:          ''

author:
  name:           'Mark Nachazel'
  url:            https://twitter.com/marknach

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
